- id: rust-fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: system
  types: [rust]
  pass_filenames: false
- id: rust-cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: system
  types: [rust]
  pass_filenames: false
- id: rust-build
  name: build
  description: Build the package.
  entry: cargo build
  language: system
  types: [rust]
  pass_filenames: false
- id: rust-no-warnings
  name: no-warnings
  description: Build the package and error on warnings.
  entry: cargo rustc -- -D warnings
  language: system
  types: [rust]
  pass_filenames: false
- id: rust-clippy
  name: clippy
  description: Lint rust source files.
  entry: cargo clippy
  language: system
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
- id: bicep-fmt
  name: Format Bicep Files
  description: This hook format all bicep files.
  entry: bash -c 'for n in $(seq 0 "$#"); do az bicep format --file "${!n}"; done'
  require_serial: true
  language: system
  types: [file]
  files: \.(bicepparam$|bicep)$
- id: bicep-lint
  name: Lint Bicep Files
  description: This hook lint all bicep files.
  entry: bash -c 'for n in $(seq 0 "$#"); do az bicep lint --file "${!n}"; done'
  require_serial: true
  language: system
  types: [file]
  files: \.(bicepparam$|bicep)$
- id: prettier
  name: prettier
  description: Format files with prettier.
  entry: prettier --ignore-unknown --write
  language: node
  additional_dependencies: ["prettier@latest"]
