repos:
- hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-private-key
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
- hooks:
  - id: commitizen
    additional_dependencies: ['cz-conventional-gitmoji']
  - id: commitizen-branch
    additional_dependencies: ['cz-conventional-gitmoji']
    stages:
    - post-commit
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.22.0
